#! /bin/bash

# get the directory in which this script is located
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# try to guess a suitable python executable
for pye in python3 python2.7 python2.6 python2 python; do
  type -P $pye &>/dev/null && break
done

# run python on the provided script
exec $pye $DIR/ughub.py "$@"
